### PR TITLE
Use a non-archived mafsa fork

### PR DESCRIPTION
**Pull request by fenollp**
We've found crashes that @Shugyousha's [unmerged work](https://github.com/smartystreets-archives/mafsa/pull/8) fixes.

The original mafsa repo is now archived and doesn't seem ready to accept PRs anymore. I just picked a fork that had the changes I need on master.
Maybe @Shugyousha would prefer to merge their branch on their own mafsa repo so it is their repo that is depended on?

### CODE REVIEW

**Comment by fenollp** [comment]
For anyone interested:
```
go mod edit -replace=github.com/smartystreets/mafsa@master=github.com/Shugyousha/mafsa@unicodeserializationfixes
```

**Comment by Shugyousha** [comment]
I haven't looked at this code in years and I am not sure I can maintain a fork. What I can do though is merge their changes and mine and push them to master on my repo. That way at least people can depend on master and don't have to depend on code on some feature branch.

If I do this and actual PRs are coming in I will see if I can deal with them properly. If I cannot, people are free to fork again.

Does that make sense for you?

**Comment by fenollp** [comment]
Sounds great to me

**Comment by Shugyousha** [comment]
I have merged smartystreets' changes and added my fixes on top. I have pushed the result to my master branch. I may decide to tag some version at one point but this merge is the first step.

**Comment by Shugyousha** [comment]
I have now tagged version v0.1.0 on the master branch.

**Comment by fenollp** [comment]
Thanks! I've switch to use your fork.

**Comment by Shugyousha** [comment]
Cool, thanks!

**Comment by fenollp** [comment]
@dvirsky Anything I can do to get this merged? Thanks

**Comment by dvirsky** [comment]
Sorry, I didn't notice the PR :) I'll try to review it soon.

**Comment by dvirsky** [comment]
BTW I've ported this project to C a few years ago and optimized it considerably, this version is pretty suboptimal. Not sure how the current license will work for you though, but the library itself is much much better. https://github.com/RediSearch/RediSearch/tree/master/src/trie

**Comment by fenollp** [comment]
Oh so that's how they're related :) I'll look into replacing our usage by RediSearch as our corpus keeps increasing.

Thanks!

**Pull request merged**
